# 12. Highly Divisible Triangular Number

"""
The sequence of triangle numbers is generated by adding the natural numbers.

So the 7th triangle number would be:
 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28.

The first ten terms would be:
1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...

Let us list the factors of the first seven triangle numbers:

 1: 1
 3: 1,3
 6: 1,2,3,6
10: 1,2,5,10
15: 1,3,5,15
21: 1,3,7,21
28: 1,2,4,7,14,28
36: 1,2,3,4,6,9,12,18,36
45: 1,3,5,9,15,45
55, 1,5,11,55
66: 1,2,3,6,11,22,33
78: 1,2,3,6,13,26,39,78
91: 1,7,13,91
105: 1,3,5,7,15,21,35,106
We can see that 28 is the first triangle number to have over five divisors.

What is the value of the first triangle number to have over five hundred divisors?
"""
from _timeit import timeit

# Brainstorm
"""
The brute force method is to continuously iterate through the triangle numbers and count the number of divisors.
However, we can save computational process by storing the number of divisors for each number we encounter.
"""

@timeit
def TriangleNumberDivisor(divisor):
    count = 1
    triangle_num = 1
    divisor_len = 2
    found = False
    while (not found):
        count += 1
        triangle_num += count
        triangle_sqr = int(triangle_num**(1/2))


        divisors = 0
        for i in range(1, triangle_sqr + 1): # Must be divided by primes
            if triangle_num % i == 0:
                if triangle_num // i == i:
                    divisors += 1
                else:
                    divisors += 2
        if divisors >= divisor:
            return triangle_num


print(TriangleNumberDivisor(500))